/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.1
 */
#include "IvoryTest.h"

struct SysTime sysTime;

void loop()
{
    uint16_t n_deref0 = (&sysTime)->ticks;
    uint16_t n_r1 = allLEDs((uint8_t) (uint16_t) (n_deref0 % (uint16_t) 2U));
    
    shift16(n_r1);
    updateTime(&sysTime);
    delay((uint32_t) 1U);
    return;
}

void setup()
{
    pinMode((uint8_t) 13U, (uint8_t) 1U);
    pinMode((uint8_t) 6U, (uint8_t) 1U);
    pinMode((uint8_t) 3U, (uint8_t) 1U);
    pinMode((uint8_t) 4U, (uint8_t) 1U);
    pinMode((uint8_t) 5U, (uint8_t) 1U);
    pinMode((uint8_t) 2U, (uint8_t) 1U);
    digitalWrite((uint8_t) 5U, (uint8_t) 0U);
    digitalWrite((uint8_t) 5U, (uint8_t) 1U);
    return;
}

void shift16(uint16_t n_var0)
{
    digitalWrite((uint8_t) 3U, (uint8_t) 0U);
    digitalWrite((uint8_t) 4U, (uint8_t) 0U);
    shiftOut((uint8_t) 2U, (uint8_t) 3U, (uint8_t) 1U,
             (uint8_t) (uint16_t) ((uint16_t) (n_var0 >> (uint16_t) 8U) &
                                   (uint16_t) 255U));
    shiftOut((uint8_t) 2U, (uint8_t) 3U, (uint8_t) 1U,
             (uint8_t) (uint16_t) (n_var0 & (uint16_t) 255U));
    digitalWrite((uint8_t) 6U, (uint8_t) 1U);
    digitalWrite((uint8_t) 4U, (uint8_t) 1U);
    digitalWrite((uint8_t) 4U, (uint8_t) 0U);
    digitalWrite((uint8_t) 6U, (uint8_t) 0U);
}

uint16_t allLEDs(uint8_t n_var0)
{
    uint16_t n_local0 = (uint16_t) 0U;
    uint16_t* n_ref1 = &n_local0;
    
    COMPILER_ASSERTS((bool) ((bool) ((int32_t) ((int32_t) 5 - (int32_t) 1) <
                                     (int32_t) 5) &&
                             (bool) ((int32_t) -(int32_t) 1 <=
                                     (int32_t) ((int32_t) 5 - (int32_t) 1))));
    COMPILER_ASSERTS((bool) ((bool) ((int32_t) 0 < (int32_t) 5) &&
                             (bool) ((int32_t) -(int32_t) 1 <= (int32_t) 0)));
    for (int32_t n_ix2 = (int32_t) ((int32_t) ((int32_t) 5 - (int32_t) 1) %
                                    (int32_t) 5); n_ix2 >=
         (int32_t) ((int32_t) 0 % (int32_t) 5);