/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.1
 */
#ifndef __IVORYTEST_H__
#define __IVORYTEST_H__
#ifdef __cplusplus
extern "C" {
#endif
#include <test.h>
#include "ivory.h"
struct SysTime {
    uint16_t seconds;
    uint16_t periods;
    uint16_t ticks;
} __attribute__((__packed__));
extern struct SysTime sysTime;
void loop();
void setup();
void shift16(uint16_t n_var0);
uint16_t allLEDs(uint8_t n_var0);
void updateTime(struct SysTime* n_var0);
bool pwm(uint16_t n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __IVORYTEST_H__ */